=pod

=encoding UTF-8

=head1 NAME

Object::Properties - minimal-ceremony class builder

=head1 VERSION

version 0.001

=head1 SYNOPSIS

 package Someclass;
 use Object::Properties foo => \&_check_foo, qw( bar baz );
 sub _check_foo {
     croak 'Someclass "bar" property may not be a reference'
         if ref $_[1];
 }

Meanwhile, elsewhere:

 my $obj = Someclass->new( bar => 7 );
 say $obj->bar; # 7
 $obj->foo = 42;
 say $obj->foo; # 42
 $obj->foo = \1; # croaks
 $obj->bar = 42; # dies

=head1 DESCRIPTION

This is a class builder with a very minimal API and support for efficient
validated lvalue accessors.

=head1 INTERFACE

The module's C<import> method accepts a list of field names and sets up an
accessor for each of them in the package it was invoked from:

 use Object::Properties qw( foo bar );

Fields are read-only by default, unless the name of the field is followed by
a reference to a function, in which case it will be a read-write field:

 use Object::Properties page => \&_check_page;

Any write to a read-write field will invoke the function associated with it,
with the the object instance passed to it as its first argument and the new
value for the field as its second argument. The function may do with this value
whatever it wishes to:

 sub _check_page {
     my ( $self, $value ) = @_;
     croak 'Cannot page past the end' if $value > $self->max_page;
 }

The return value of this function is very important: it signals whether the
function has fully handled the value itself. A true value means everything is
done. A false value means that the new field value should be stored. This is so
you can write a simple validator for the value (illustrated above) just as well
as handle the whole assignment yourself:

 sub _munge_hostname {
     my ( $self, $value ) = @_;
     $self->{'hostname'} = lc $value;
     1;
 }

A class method called C<NEW> will be exported into your package. This method
creates a blessed hash from its arguments and invokes the function associated
with each writable field supplied by the caller (in some random order), so that
a new instance will be validated during construction. You will probably want to
call C<NEW> from your constructor:

 sub new { shift->NEW( @_ ) }

But if that is all your constructor would do, you will not need to write it:
C<Object::Properties::Base> contains such a C<new> method and will be added to
your C<@ISA> if that is empty.

=head1 SEE ALSO

The biggest difference between this module and all of its competition is that
it is decidedly B<not> pure-Perl. This is inevitably so due to the desire for
efficient validated lvalue accessors. Might as well go all out and get very
fast read-only accessors too, then.

=over 4

=item * L<Object::Tiny>

=item * L<Object::Tiny::RW>

=item * L<Object::Tiny::Lvalue>

=item * L<Class::Tiny>

=item * L<Moo>

=item * L<MooX::LvalueAttribute>

=back

=head1 AUTHOR

Aristotle Pagaltzis <pagaltzis@gmx.de>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2015 by Aristotle Pagaltzis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
